### PR TITLE
Fixing OSC mass matrix indexing

### PR DESCRIPTION
**Pull request by amandlek**
- The current indexing of the mass matrix is wrong. This should fix it.

### CODE REVIEW

**Comment by yukezhu** [comment]
I don't quite understand the difference between `qpos_index`, `qpos_vel`, and `joint_index`. In what scenarios they are different? In my experiments they had the same values.

**Comment by amandlek** [comment]
Try using a position indicator - that will change the qpos and qvel index values.

**Comment by yukezhu** [comment]
Do you mean that position indicators have `qpos` but not `qvel`? I found using `qvel` is confusing here. Why not `joint_index`?

**Comment by amandlek** [comment]
The qvel indices are how you are supposed to index the mass matrix, as far as I understand. Perhaps @cremebrule @roberto-martinmartin could comment.

**Comment by yukezhu** [comment]
So are we ready to merge this fix?

**Comment by cremebrule** [comment]
Looks good to me.

**Pull request merged**
